# Generated by Django 2.2.1 on 2019-05-13 09:14

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatlabLogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('app_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='App Name')),
                ('requested_uuid', models.CharField(blank=True, max_length=255, null=True, verbose_name='UUID')),
                ('requested_ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='Requested IP')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='File Name')),
                ('dependency_files', models.TextField(blank=True, null=True, verbose_name='Dependent Files List')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
