Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    
    config.vm.box = "hashicorp/bionic64"
    
    config.vm.network "private_network", ip: "192.168.10.10"
    config.vm.network "forwarded_port", guest: 8088, host: 8088
  
    config.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end
  